### ISSUE TITLE
Prerequisites are not met. Unable to identify your operating system requirements

### ISSUE THREAD

**Issue by RasheedAZ** [Taryck/idrive#4]
Hi. When I run account_setting.pl, it says:

"Prerequisites are not met. Unable to identify your operating system requirements"

Can you please help/advise? Thanks.

Linux pop-os 5.15.15-76051515-generic #202201160435~1642693824~21.10~97db1bb SMP Thu Jan 20 17:35:05 U x86_64 x86_64 x86_64 GNU/Linux

**Comment by Taryck** [comment]
Hi,

What is your ooperating system?
Did you try the official script from idrive ?

Taryck

**Comment by RasheedAZ** [comment]
Thanks for replying. Pop!_OS 21.10.

Yes they said they're not officially supporting Pop OS unfortunately :( but they provided a custom script that worked after a day and now it's backing up :)

Thanks. Would be great it there was an easy to use hassle free app on Linux for online backup. Maybe you guys could make a flatpak app and make it available on flathub so it would work on all of the major Linux distros like the Mega backup & sync client...? I'm on the 5TB iDrive plan and hope the Linux experience gets better :)

**Comment by agent-kimbley** [comment]
> Thanks for replying. Pop!_OS 21.10.
> 
> Yes they said they're not officially supporting Pop OS unfortunately :( but they provided a custom script that worked after a day and now it's backing up :)
> 
> Thanks. Would be great it there was an easy to use hassle free app on Linux for online backup. Maybe you guys could make a flatpak app and make it available on flathub so it would work on all of the major Linux distros like the Mega backup & sync client...? I'm on the 5TB iDrive plan and hope the Linux experience gets better :)

Where get the custom script,I got same isuse now@

**Comment by Taryck** [comment]
Ask To official idrive support or as I do modify your Perl script as they
only build the file list to backup.
Backup is perform by the binary file provide with the script

Le mer. 20 avr. 2022 à 11:30, agent-kimbley ***@***.***> a
écrit :
