### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by marshalleq** [Taryck/idrive#6]
I'm getting "Failed to authenticate user "myemailhere". Username or Password not found. Please try again." then it just bails me out.

I can log in via the web console perfectly.  I've taken out the dashes that were in the password in case it's that, but nope.

There are no firewall blocks or anything.  I've also run the internal update script given that this is a 6 month old container and there are a lot of updates since then.

Doing this on unraid, but given how many containers I have and how long I've been running them I don't think I've missed anything (i.e. I'm not a noob).

**Comment by marshalleq** [comment]
I should mention I am doing client side encryption, in case there's some weird thing to do for encryption key as part of login, but from what I've seen there isn't.

**Comment by dsiminiuk** [comment]
login with username for the account which may not be the current email. Username for the account is immutable, email can be changed.

**Comment by marshalleq** [comment]
Thanks for coming back so quickly!  

OK, but if I can login via the web page that would be it?  I only just signed up today, so there's only been one email address.

**Comment by dsiminiuk** [comment]
Then this is likely not the problem.

**Comment by marshalleq** [comment]
I just checked on my account page and it clearly says username = the email I'm using so I guess it's not that. :(.

**Comment by marshalleq** [comment]
I'll try it with the Mac agent and see if that works.  Maybe it needs a kick first.

**Comment by marshalleq** [comment]
Doesn't work in Mac client either, that's good news for you!  Not so good for me lol.  Perhaps their backup targets sync accounts more slowly.  I did do a 'reset account' on my account because I accidentally forgot to choose private keys the first time, but still, same email.  Oh well, looks like we can close this anyway, thanks!

**Comment by Taryck** [comment]
For your information I use this script every day with client encryption on Linux CentOS.
You could try first to use the official linux script that you can find here :
https://www.idrive.com/linux-backup-scripts
Keep in mind that you must first "install" your account using : account_setting.pl
The original scripts are very intrusive in a Linux point of view, thats why I've modified it.
